language: python
sudo: required
dist: xenial
python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - 3.9-dev

install:
  - pip install -U poetry
  - poetry install

jobs:
  include:
    - stage: check
      script: flake8 --ignore E501 openpyscad

script:
  - nosetests  --with-coverage --cover-package=openpyscad

after_success:
  - coveralls

before_deploy:
  - git config --local user.name "taxpon"
  - git config --local user.email "taxpon@gmail.com"
  - poetry version minor
  - export RELEASE_VERSION=$(poetry version | cut -d ' ' -f 2)
  - git tag -a "$RELEASE_VERSION" -m "$RELEASE_VERSION"

deploy:
  provider: script
  script: poetry publish -u ${PYPI_USERNAME} -p ${PYPI_PASSWORD} --build
  skip_cleanup: true
  on:
    branch: master

after_deploy:
  - git checkout develop
  - git commit -a -m "Bump version"
  - git push origin develop
  - git push origin --tags

stages:
  - check
  - test
  - name: deploy
    if: branch = master AND type != pull_request

notifications:
  email: false